// react-dashboard/src/components/TopCard.js
function TopCard() {
    return (  
        <div className="relative w-96 bg-white ml-16 p-8">
            <div className="flex justify-between mb-6">
                <div className="flex flex-col border-l-8 border-[#405dcf] pl-6">
                <span className="text-[#b6b6b6] text-2xl">Customers</span>
                <span className="text-[#181f2e] font-bold text-3xl">1,456</span>
                </div>
                <div className="h-10 w-10 bg-[#eceffa]"></div>
            </div>

            <span className="font-bold text-[#53b289]">+6.5%</span> Since last week
        </div>
    );
  }
  
  export default TopCard;

// vue-dashboard/src/components/TopCard.vue
<template>
    <a href="#" class="block max-w-sm p-6 bg-white border border-gray-200 shadow-md hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
        <div class="border-l-8 border-[#405dcf] pl-6 flex">
            <div>
                <span class="text-[#b6b8be] text-xl">Customers</span>
                <br/>
                <span class="text-[#181f2e] font-bold text-3xl">1,456</span>
            </div>
            <div class="h-10 w-10 bg-[#eceffa] ml-16"></div>
        </div>
        
        <div class="mt-4 text-[#b6b8be]">
            <span class="text-[#53b289] font-bold">+6.5%</span> Since last week
        </div>
    </a>
</template>
